#!/usr/bin/env bash
# install.sh — ONE-COMMAND installer for OpenWebUI
# Generated by Spryntworks Platform. No configuration needed — defaults work.
set -euo pipefail

echo "=============================================="
echo "  OpenWebUI — one-command install"
echo "=============================================="

# 1. Check Docker
if ! command -v docker >/dev/null 2>&1; then
    echo "[✗] Docker is not installed."
    echo "    Install it first:"
    echo "      - Windows/Mac: https://www.docker.com/products/docker-desktop/"
    echo "      - Ubuntu/Debian: sudo apt install docker.io docker-compose-plugin"
    echo "      - Other Linux: https://docs.docker.com/engine/install/"
    exit 1
fi
echo "[✓] Docker found: $(docker --version)"

# 2. Create .env from example if missing
if [ ! -f .env ]; then
    cp .env.example .env
    echo "[✓] Created .env from .env.example (edit it if you want to change settings)"
else
    echo "[✓] .env already present (keeping your settings)"
fi

# 3. Create data directory
mkdir -p data
echo "[✓] Data directory ready: ./data (your data lives here, survives updates)"

# 4. Pull + start
echo "[✓] Pulling image: ghcr.io/shraddhanandkhot/open-webui:v0.11.3-custom"
docker compose up -d --pull always

# 5. Wait for health
echo "[✓] Waiting for OpenWebUI to start..."
for i in $(seq 1 30); do
    if curl -sf -o /dev/null "http://localhost:${OPENWEBUI_PORT:-8080}/health" 2>/dev/null; then
        break
    fi
    sleep 2
done

echo
echo "=============================================="
echo "  ✓ OpenWebUI is running!"
echo
echo "  Open:  http://localhost:${OPENWEBUI_PORT:-8080}"
echo "         (if on a server: http://YOUR-SERVER-IP:${OPENWEBUI_PORT:-8080})"
echo
echo "  Next steps:"
echo "   1. Sign up — the FIRST account becomes the admin"
echo "   2. Add your model connection: Settings → Model Connections"
echo "      (paste your OpenAI / OpenRouter / Ollama key)"
echo "   3. Import the included Workspace Tools (optional):"
echo "        ./import-tools.sh <your-admin-api-key>"
echo "      (key: Settings → Admin Panel → API Keys → Generate)"
echo
echo "  Update later:  ./upgrade.sh"
echo "  Remove:        ./uninstall.sh"
echo "=============================================="
