import os
import uuid
from fpdf import FPDF

try:
    from open_webui.models.files import Files, FileForm
except ImportError:
    from open_webui.apps.webui.models.files import Files, FileForm


class ReportPDF(FPDF):
    def footer(self):
        # Position 15 mm from bottom
        self.set_y(-15)

        # Separator line
        self.set_draw_color(180, 180, 180)
        self.line(10, self.get_y(), 200, self.get_y())

        # Company name
        self.set_xy(10, self.get_y() + 2)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 80, 80)
        self.cell(0, 5, "Open WebUI")

        # By Spryntworks (italic)
        self.set_xy(10, self.get_y() + 5)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 5, "Spryntworks")

        # Page number
        self.set_xy(170, self.get_y() - 5)
        self.set_font("Helvetica", "", 9)
        self.cell(30, 10, f"Page {self.page_no()}", align="R")


class Tools:
    def __init__(self):
        pass

    async def create_financial_report(
        self,
        title: str,
        summary: str,
        dynamic_sections: str,
        filename: str,
        __user__: dict = None,
        __event_emitter__=None,
    ) -> str:
        """
        Generate a PDF financial report and register it in Open WebUI Files.
        """

        # ------------------------------------------------------------------
        # Ensure PDF extension
        # ------------------------------------------------------------------
        if not filename.lower().endswith(".pdf"):
            filename = filename.rsplit(".", 1)[0] + ".pdf"

        # ------------------------------------------------------------------
        # Upload folder
        # ------------------------------------------------------------------
        upload_dir = os.path.abspath("./data/uploads")
        os.makedirs(upload_dir, exist_ok=True)

        file_id = str(uuid.uuid4())
        unique_filename = f"{file_id}_{filename}"
        file_path = os.path.join(upload_dir, unique_filename)

        # ------------------------------------------------------------------
        # Create PDF
        # ------------------------------------------------------------------
        pdf = ReportPDF()

        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(
            0,
            8,
            "Generated by Open WebUI Report Generator",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        pdf.ln(5)

        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 7, summary)

        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Key Findings", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 11)

        for line in dynamic_sections.split("\n"):
            pdf.multi_cell(0, 7, line)

        pdf.ln(10)

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)

        pdf.multi_cell(
            0,
            6,
            "Confidential - For Internal Review & Client Use Only",
        )

        pdf.output(file_path)

        # ------------------------------------------------------------------
        # Register with Open WebUI
        # ------------------------------------------------------------------

        user_id = __user__.get("id") if __user__ else "admin"

        file_form = FileForm(
            id=file_id,
            filename=filename,
            path=file_path,
            data={
                "title": title,
                "summary": summary,
                "content": dynamic_sections,
            },
            meta={
                "name": title,
                "content_type": "application/pdf",
                "size": os.path.getsize(file_path),
                "description": summary,
                "tags": [
                    "financial-report",
                    "generated",
                    "pdf",
                ],
            },
        )

        result = await Files.insert_new_file(user_id, file_form)

        if result is None:
            return "ERROR: Failed to register PDF inside Open WebUI."

        # return the file object; the patched middleware attaches it to the
        # chat message natively as a downloadable file
        return {
            "output": f"PDF report created successfully. Filename: {filename}",
            "files": [
                {
                    "id": file_id,
                    "filename": filename,
                    "name": filename,
                    "url": file_id,
                    "content_type": "application/pdf",
                    "size": os.path.getsize(file_path),
                    "type": "file",
                    "status": "processed",
                }
            ],
        }
